name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3
        id: release
        with:
          release-type: node
          bump-patch-for-minor-pre-major: true
          token: ${{ secrets.RELEASE }}
          labels: "Pending Release"
          release-labels: "Released"
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "18.x"
          cache: yarn
          registry-url: https://registry.yarnpkg.com/

        if: ${{ steps.release.outputs.release_created }}
      - run: yarn --immutable && yarn build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm link
        if: ${{ steps.release.outputs.release_created }}
      - run: ariaa
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"
          yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}